[server]
address = ":5354"
domain = "127.0.0.1"


[fx]
enabled = true

# Frequency to refresh the currency conversion data from the API.
refresh_interval = "6h"

snapshot_enabled = true
snapshot_file = "data/fx.snapshot"


[ip]
enabled = true

[pi]
enabled = true

[dict]
enabled = true

# path to wordnet data files directory
# https://wordnetcode.princeton.edu/3.0/WNdb-3.0.tar.gz
# directory should have files - data.noun, data.adj, data.adv, data.verb
wordnet_path = "data/wordnet"

# Maximum results to show per part-of-speech type (noun, verb etc.)
max_results = 5

[dice]
enabled = true

[rand]
enabled = true